;BKTurbo8_x64.exe CO C:\Users\Den\YandexDisk\home\src\pdp11\account1\calc1.asm

			RT1=177706 ; ADR REG SETTING TIMER
			RT2=177710 ;ADR REG COUNTTIMER
			RT3=177712 ;ADR REG CONTROL

			CALL SET1 ;_DONE SET PROGRAMM 10 OR 100 MANTIS; NUMBER OF CORRECT RESULTS TO END
			CALL RUNCOUNT ;RUN SYSTEM TIMER
;			CALL SET2 ;GENERATE NUMBER FOR ONE EXAMPLE
;			CALL START ;RUN PROGRAMM
;			CALL ENDGAME ;GO END
			EMT 6
	
	
		
SET1:		CALL CLRS1 ;CLEAR SCREEN      			_DONE
			CALL WELC1 ;				      		_DONE
			CALL ADDNUMB1 ; ADD LEVEL     			_DONE
			CALL WELC2 ;
			CALL ADDNUMB2 ; ADD COUNT EXAMPLE     	_DONE
			CALL CON10TO8 ; ADD COUNT EXAMPLE     	_DONE
			RET

;ACTIVATION TIMER
RUNCOUNT:	MOV #1747,RT1 ;SETUP 999DEC NUMBER
			MOVB #20,RT3 ;T=2.812
	
			MOV #12,R1 ;ENTER BUTTON
			MOV #40,R2 ;ПРОБЕЛ
			MOV #ARR1,R3 ;ADR ARR1
1:			EMT 6
			MOV RT2,(R3)+ ;WRITE RND TO ARR1
;	MOV @R1,R4 ;WRITE RND TO ARR1
			CMP R0,R1
	
			BEQ 1
			CMP R0,R2
			BNE 1
			HALT
ARR1: .WORD 0
		









ADDNUMB1:   MOV #SETTING1,R3 ;LOAD ADR #SETTING1
			EMT 6
			NOP
			CMPB #61,R0		 
			BNE 3$
			MOVB #1,(R3) ;LOAD NUMBER LEVEL DEFF
			EMT 16			;INT KEYBOARD
			BR 4$
3$:			MOVB #2,(R3)
			EMT 16			;INT KEYBOARD
4$:			MOV #12,R0
			EMT 16
			RET

ADDNUMB2:	MOV #NUMB10ADR,R1 ;LOAD ADR SETTING
			MOV #5377,R2 ; У Зальцмана 5377 это 12 код ВВОДа и 256 байт резерва
			EMT 10
			CLR R3
			;INC R1 ;  ------DELTE 12(enter)
			MOV R3,(R1) ; --
			RET
			
;STARt PROCEDURE 10 TO 8			
CON10TO8:	CLR R5 ; NUMB8
			
			MOV #MANTIS,R0 ;ADD ADR MANTIS OCT
			MOV #NUMB10ADR,R1 ;ADD ADR ARR SYMBOL DEC NUMB
			;SWAB (R1)
			MOV #0,R2 ; FOR FIND POINT ZERO ADR ARR2
			CLR R4 ;COUNT LENGTH NUB DEC
			;TODO R3 ЗАНЯТ ПРИМЕНИТЬ СТЕК
			;MOV R3,-(SP) ;CLEAR R3  DATA IN STACK
			CLR R3
5$:	 		MOVB (R1)+,R3
			INC R4 ;COUNT LENGTH NUB DEC
			CMP R2,R3 ; FOR FIND POINT ZERO ADR ARR2
			BMI 5$ ;N=1
			
			DEC R4 ;CORRECT COUNT ЕСЛИ ЭТОГО НЕ СДЕЛАТЬ ТО ЦИФРА БУДЕТ УВЕЛИЧЕНОЙ НА ОДНУ ЛИШНЕЮ МАНТИССУ
			SUB R4,R1 ;CORRECT ADR
6$:		    MOV #60,R2 ; CODE SYMBOL 0
7$:		    ADD (R0),R5 ; ADD MANTIS ARR1
			INC R2 ;CODE SYMBOL + 60 61 62...
			CMPB (R1),R2 ; COMPARE IS CODE SYMBOL 0
			BNE 7$
			DEC R4 ;COUNT LENGTH NUB DEC
			BEQ 8$ ;IF COUNT 0 TO END 
			ADD #2,R0 ;NEXT MANTIS
			SUB #1,R1 ;NEXT SYMBOL
			BR 6$
8$: 		MOV #SETTING1,R3 ;LOAD ADR #SETTING1
			inc R3
			;MOV (SP)+,R3 ;RECOVERY DATA (ADR #SETTING1+1BYTE)
			MOVB R5,(R3)	
			RET		

WELC1:  	MOV #TEXT1,R1
2$:	   		MOVB (R1)+,R0
			CMPB #0,R0
			BEQ 1$ ;GO RET
			EMT 16
			BR 2$
			CLR R3;CLR COUNT SYMBOL STRING
1$:	  	    RET

WELC2:		MOV #TEXT2,R1
9$:	   		MOVB (R1)+,R0
			CMPB #0,R0
			BEQ 10$ ;GO RET
			EMT 16
			BR 9$
			CLR R3;CLR COUNT SYMBOL STRING
10$:	    RET



CLRS1: 		MOV #14,R0 ;ENTER CODE RESET
			EMT 16
			RET 


TEXT1:  	.ASCIZ "Введите уровень сложности (1 или 2) и нажмите ВВОД "
TEXT2:		.ASCIZ "Введите количество примеров и нажмите ВВОД "
SETTING1:   .WORD 0, 0 ;МЛАДШИЙ БАЙТ КОЛ-ВО ПРИМЕРОВ,СТАРШИЙ УРОВЕНЬ СЛОЖНОСТИ
		    
MANTIS:		.WORD 1.,10.,100.,1000.
NUMB10ADR:  .WORD 0, 0, 0
.END
		  