;BKTurbo8_x64.exe CO C:\Users\Den\YandexDisk\home\src\pdp11\account1\calc1.asm

			RT1=177706 ; ADR REG SETTING TIMER
			RT2=177710 ;ADR REG COUNTTIMER
			RT3=177712 ;ADR REG CONTROL

			CALL SET1 ;_DONE SET PROGRAMM 10 OR 100 MANTIS; NUMBER OF CORRECT RESULTS TO END
			CALL RUNCOUNT ;_DONE RUN SYSTEM TIMER
			CALL SET2 ;_TODO GENERATE NUMBER FOR ONE EXAMPLE
;			CALL START ;RUN PROGRAMM
;			CALL ENDGAME ;GO END
			EMT 6
	
	
		
SET1:		CALL CLRS1 ;CLEAR SCREEN      			_DONE
			CALL WELC1 ;				      		_DONE
			CALL ADDNUMB1 ; ADD LEVEL     			_DONE
			CALL WELC2 ;
			CALL ADDNUMB2 ; ADD COUNT EXAMPLE     	_DONE
			CALL CON10TO8 ; ADD COUNT EXAMPLE     	_DONE
			MOV #SETTING2,R0
			MOV #SETTING1,R1
			MOV (R1)+,(R0)+
			MOV (R1)+,(R0)+
			RET

;ACTIVATION TIMER 144-100 1747-1000
RUNCOUNT:	MOV #SETTING1,R1
			CMPB #1,(R1) ;LOAD USER DEFFICTIVY - >1 BYTE SETTING1
			BEQ 11$
			MOV #1747,RT1 ;SETUP 999DEC NUMBER
			BR 12$
11$:		MOV #144,RT1 ;SETUP 100DEC NUMBER
12$:		MOVB #20,RT3 ;T=2.812	P/S:ZALCMAN		
			RET
;GENERATE NUMBER FOR ONE EXAMPLE
SET2:		CALL WELC3 ;_TODO 152-97 ?
			CALL ADDRND1 ;GO 1 NUMBER IS RT2
			CALL CLRS2 ;CLEAR ARR TO NUMB10ADR
			CALL ADDNUMB2
			CALL CON10TO8
			CALL ADDRND2 ;GO 2 NUMBER IS RT2
			CALL CALC
			MOV #SETTING1,R1
			INC R1
			CMP #67,(R1)
			BEQ 16$
			CALL VARFALSE
			BR 17$
16$:		CALL VARTRUE
17$:		EMT 6


ADDRND1:	MOV #RNDCALC,R0
			MOV @RT2,(R0)
			RET
ADDRND2:	MOV #RNDCALC,R0
			INC R0
			MOV @RT2,(R0)
			RET
CALC:		MOV #PROCEDURE,R0
			CMP #177777,R0
			BMI 22$
			CALL CALCADD
			RET
22$:		CALL CALCSUB
			RET
CALCADD:	CLR R0
			CLR R1
			CLR R2
			MOV #RNDCALC,R0
			MOV (R0)+,R1
			MOV (R0)+,R2
			ADD R1,R2
			MOV R2,(R0)
			CLR R0
			MOV #PROCEDURE,R0
			COM (R0)
			RET
CALCSUB:	CLR R0
			CLR R1
			CLR R2	
			MOV #RNDCALC,R0
			MOV (R0)+,R1
			MOV (R0)+,R2
			CMP R1,R2
			BMI 23$
			SUB R2,R1
			MOV R1,(R0)
			CLR R0
			MOV #PROCEDURE,R0
			RET
23$:		SUB R1,R2
			MOV R2,(R0)
			CLR R0
			MOV #PROCEDURE,R0
			RET
			
ADDNUMB1:   MOV #SETTING1,R3 ;LOAD ADR #SETTING1
			EMT 6
			NOP
			CMPB #61,R0		 
			BNE 3$
			MOVB #1,(R3) ;LOAD NUMBER LEVEL DEFF
			EMT 16			;INT KEYBOARD
			BR 4$
3$:			MOVB #2,(R3)
			EMT 16			;INT KEYBOARD
4$:			MOV #12,R0
			EMT 16
			RET

ADDNUMB2:	MOV #NUMB10ADR,R1 ;LOAD ADR SETTING
			MOV #5377,R2 ; У Зальцмана 5377 это 12 код ВВОДа и 256 байт резерва
			EMT 10
			CLR R3
			;INC R1 ;  ------DELTE 12(enter)
			MOV R3,(R1) ; --
			RET
			
;STARt PROCEDURE 10 TO 8			
CON10TO8:	CLR R5 ; NUMB8
			
			MOV #MANTIS,R0 ;ADD ADR MANTIS OCT
			MOV #NUMB10ADR,R1 ;ADD ADR ARR SYMBOL DEC NUMB
			;SWAB (R1)
			MOV #0,R2 ; FOR FIND POINT ZERO ADR ARR2
			CLR R4 ;COUNT LENGTH NUB DEC
			;TODO R3 ЗАНЯТ ПРИМЕНИТЬ СТЕК
			;MOV R3,-(SP) ;CLEAR R3  DATA IN STACK
			CLR R3
5$:	 		MOVB (R1)+,R3
			INC R4 ;COUNT LENGTH NUB DEC
			CMP R2,R3 ; FOR FIND POINT ZERO ADR ARR2
			BMI 5$ ;N=1
			
			DEC R4 ;CORRECT COUNT ЕСЛИ ЭТОГО НЕ СДЕЛАТЬ ТО ЦИФРА БУДЕТ УВЕЛИЧЕНОЙ НА ОДНУ ЛИШНЕЮ МАНТИССУ
			SUB R4,R1 ;CORRECT ADR
6$:		    MOV #60,R2 ; CODE SYMBOL 0
7$:		    ADD (R0),R5 ; ADD MANTIS ARR1
			INC R2 ;CODE SYMBOL + 60 61 62...
			CMPB (R1),R2 ; COMPARE IS CODE SYMBOL 0
			BNE 7$
			DEC R4 ;COUNT LENGTH NUB DEC
			BEQ 8$ ;IF COUNT 0 TO END 
			ADD #2,R0 ;NEXT MANTIS
			SUB #1,R1 ;NEXT SYMBOL
			BR 6$
8$: 		MOV #SETTING1,R3 ;LOAD ADR #SETTING1
			inc R3
			;MOV (SP)+,R3 ;RECOVERY DATA (ADR #SETTING1+1BYTE)
			MOVB R5,(R3)	
			RET	
			

WELC1:  	MOV #TEXT1,R1
2$:	   		MOVB (R1)+,R0
			CMPB #0,R0
			BEQ 1$ ;GO RET
			EMT 16
			BR 2$
			CLR R3;CLR COUNT SYMBOL STRING
1$:	  	    RET

WELC2:		MOV #TEXT2,R1
9$:	   		MOVB (R1)+,R0
			CMPB #0,R0
			BEQ 10$ ;GO RET
			EMT 16
			BR 9$
			CLR R3;CLR COUNT SYMBOL STRING
10$:	    RET

WELC3:		MOV #TEXT3,R1
14$:   		MOVB (R1)+,R0
			CMPB #0,R0
			BEQ 13$ ;GO RET
			EMT 16
			BR 14$
			CLR R3;CLR COUNT SYMBOL STRING
13$:	    RET

VARFALSE:	MOV #TEXT4,R1
19$:   		MOVB (R1)+,R0
			CMPB #0,R0
			BEQ 18$ ;GO RET
			EMT 16
			BR 19$
			CLR R3;CLR COUNT SYMBOL STRING
18$:	    RET

VARTRUE:	MOV #TEXT5,R1
21$:   		MOVB (R1)+,R0
			CMPB #0,R0
			BEQ 20$ ;GO RET
			EMT 16
			BR 21$
			CLR R3;CLR COUNT SYMBOL STRING
20$:	    RET


CLRS1: 		MOV #14,R0 ;ENTER CODE RESET
			EMT 16
			RET
;CLEAR ARR TO NUMB10ADR
CLRS2:		MOV #NUMB10ADR,R1
			MOV #4,R2
15$:		CLR (R1)+
			DEC R2
			BNE 15$
			RET
			


TEXT1:  	.ASCIZ "Введите уровень сложности (1 или 2) и нажмите ВВОД "
TEXT2:		.ASCIZ "Введите количество примеров и нажмите ВВОД "
TEXT3:		.ASCIZ "Сколько будет 152-97: "
TEXT4:		.ASCIZ "Не правильно дурень!"
TEXT5:		.ASCIZ "Молодец, так держать!"
			.WORD 0
SETTING1:   .WORD 0, 0 ;BUFFER SETTING FOR SET1,SET2
			.WORD 0
SETTING2:	.WORD 0, 0 ;МЛАДШИЙ БАЙТ КОЛ-ВО ПРИМЕРОВ,СТАРШИЙ УРОВЕНЬ СЛОЖНОСТИ
		    .WORD 0
MANTIS:		.WORD 1.,10.,100.,1000.
NUMB10ADR:  .WORD 0, 0, 0, 0, 0
RNDCALC:    .WORD 0, 0, 0 ;1 RND NUB 2 RND NUMB 3 RESULT 1+-2
PROCEDURE:  .WORD 0  ;ТИП ВЫЧИСЛЕНИЯ 177777 +  0 -
.END
		  